name: Build And Deploy DEBUG APK To Firebase Distribution

on:
 workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Access MOVIE_API_KEY
        env:
          MOVIE_API_KEY: ${{ secrets.MOVIE_API_KEY }}
        run: echo MOVIE_API_KEY=\"MOVIE_API_KEY\" > ./local.properties

      - name: Bump version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{github.run_number}}
          #versionName: 1.0.0

      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Build Debug APK
        run: ./gradlew clean assembleDebug
        
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
